name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🛠️ Maintenance'
    labels:
      - 'maintenance'
      - 'dependencies'
      - 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'feature'
    title:
      - '/feat(.*)/'
      - '/add(.*)/'
    branch:
      - '/feat(.*)/'
      - '/add(.*)/'
  - label: 'fix'
    title:
      - '/fix(.*)/'
    branch:
      - '/fix(.*)/'
  - label: 'docs'
    title:
      - '/docs(.*)/'
    branch:
      - '/docs(.*)/'
template: |
  ## What's Changed

  $CHANGES
