# # SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2023 - present Jürgen Mülbert
#
# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
# $schema=https://json.schemastore.org/prettierrc.json
#

# General Prettier settings
printWidth: 80 # Aligns with yamllint and markdownlint defaults
tabWidth: 2 # Matches yamllint, editorconfig, and markdownlint defaults
useTabs: false # Spaces are preferred
semi: true # Use semicolons in applicable languages (e.g., JavaScript)
singleQuote: true # Use single quotes in JS and TS
quoteProps: as-needed
trailingComma: none # Avoid trailing commas for cleaner diffs
bracketSpacing: true
arrowParens: always
proseWrap: preserve # For Markdown: Avoid wrapping to allow manual control
htmlWhitespaceSensitivity: css
endOfLine: lf # Unix-style line endings for cross-platform compatibility
