---
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2024-present Jürgen Mülbert <juergen.muelbert@outlook.de>
#
version: 1.0
checks:
  - id: CICD
    enabled: true
  - id: VULNERABILITIES
    enabled: true
  # Add other checks as needed
