---
# Documentation Request
# This template is for feature requests. Please fill out as much information as possible.
# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: 2023 - 2024 Jürgen Mülbert <juergen.muelbert@outlook.de>
#
# The name of the issue template
name: Documentation
description: Report an issue related to the jm-reusable-scripts documentation.
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"
labels: [03 - Documentation]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to report an issue in the documentation.

        Only report issues with documentation here, explain if there are
        any missing topics or if you found a mistake in the documentation.

        Do **NOT** use this to ask usage questions or reporting issues with your code.

        If you have usage questions or need help solving some problem,
        please use [GitHub Discussions](https://github.com/jmuelbert/jm-reusable-scripts/discussions).

        If you're in the wrong place, here are some helpful links to find a better
        place to ask your question:

          [jm-reusable-scripts documentation with the integrated search](https://jmuelbert.github.io/developer/jm-reusable-scripts/),
          [API Reference](https://jmuelbert.github.io/developer/jm-reusable-scripts/developer/api/),
          [GitHub search](https://github.com/jmuelbert/jm-reusable-scripts),
          [jm-reusable-scripts Github Discussions](https://github.com/jmuelbert/jm-reusable-scripts/discussions),
          [jm-reusable-scripts Github Issues](https://github.com/jmuelbert/jm-reusable-scripts/issues?q=is%3Aissue),
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I included a link to the documentation page I am referring to (if applicable).
          required: true
  - type: textarea
    attributes:
      label: 'Issue with current documentation:'
      description: >
        Please make sure to leave a reference to the document/code you're
        referring to. Feel free to include names of classes, functions, methods
        or concepts you'd like to see documented more.
  - type: textarea
    attributes:
      label: 'Idea or request for content:'
      description: >
        Please describe as clearly as possible what topics you think are missing
        from the current documentation.
