# SPDX-FileCopyrightText: GitHub, Inc. and contributors
# SPDX-License-Identifier: MIT

name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  dependabot:
    name: Process Dependabot PR
    if: |
      github.actor == 'dependabot[bot]' &&
      !contains(github.event.pull_request.labels.*.name, 'do-not-merge')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      issues: write

    outputs:
      dependency-names: ${{ steps.metadata.outputs.dependency-names }}
      update-type: ${{ steps.metadata.outputs.update-type }}
      merged: ${{ steps.merge.outputs.merged }}

    steps:
      - name: 🔒 Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: 📊 Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Add Labels
        id: labels
        uses: actions/github-script@v7
        env:
          DEPENDENCY_TYPE: ${{ steps.metadata.outputs.dependency-type }}
          UPDATE_TYPE: ${{ steps.metadata.outputs.update-type }}
          ALERT_STATE: ${{ steps.metadata.outputs.alert-state }}
        with:
          script: |
            try {
              const dependencyType = process.env.DEPENDENCY_TYPE;
              const updateType = process.env.UPDATE_TYPE;
              const alertState = process.env.ALERT_STATE;

              const labels = [];

              // Add dependency type label
              if (dependencyType === 'direct:production') {
                labels.push('production-dependency');
              } else {
                labels.push('development-dependency');
              }

              // Add update type label
              if (updateType.includes('version-update:semver-patch')) {
                labels.push('patch-update');
              } else if (updateType.includes('version-update:semver-minor')) {
                labels.push('minor-update');
              } else if (updateType.includes('version-update:semver-major')) {
                labels.push('major-update');
              }

              // Add security label if needed
              if (alertState === 'fixed') {
                labels.push('security');
              }

              const pr = context.payload.pull_request;
              if (!pr) {
                throw new Error('This workflow must be triggered by a pull request event.');
              }

              // Add labels to PR
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });

              console.log('Labels added successfully:', labels);
            } catch (error) {
              console.error('Failed to add labels:', error.message);
              core.setFailed(error.message);
            }

      - name: ✅ Auto-approve PR
        id: approve
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          contains(steps.metadata.outputs.dependency-names, 'test-dependencies')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: '✅ Automatically approved based on dependency type and update scope'
            });

      - name: 🔄 Enable Auto-merge
        id: merge
        if: |
          steps.approve.outcome == 'success' &&
          !contains(steps.metadata.outputs.dependency-names, 'blocked-deps')
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash',
                commit_title: `chore(deps): ${context.payload.pull_request.title}`,
                commit_message: 'Auto-merged by Dependabot 🤖'
              });
              core.setOutput('merged', 'true');
            } catch (error) {
              console.log(`Failed to merge: ${error.message}`);
              core.setOutput('merged', 'false');
            }

      - name: 📝 Add Merge Comment
        if: steps.merge.outputs.merged == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `✅ Successfully auto-merged this PR!\n\nUpdated dependencies:\n${steps.metadata.outputs.dependency-names}`
            });

  notify:
    needs: dependabot
    if: always() && needs.dependabot.result != 'skipped'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 🔔 Notify on Failure
        if: needs.dependabot.result == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '❌ Auto-merge workflow failed. Please check the workflow logs.'
            });
